name: frontend_pos
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'  # Cambiado para mejor compatibilidad

dependencies:
  flutter:
    sdk: flutter

  # Dependencias principales
  shared_preferences: ^2.2.2
  camera: ^0.10.5+1  # Versión compatible
  google_mlkit_barcode_scanning: ^0.6.0  # Versión compatible
  
  # El resto de tus dependencias
  google_fonts: ^6.0.0
  mobile_scanner: ^7.1.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  intl: ^0.20.2
  http: ^1.5.0
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.1.2
  syncfusion_flutter_charts: ^31.1.19
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true