name: frontend_pos
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # 👇 Aquí va shared_preferences fuera del bloque flutter
  shared_preferences: ^2.2.2

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  intl: ^0.20.2
  http: ^1.5.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
