name: frontend_pos
description: "KioskoGo - Aplicación de punto de venta"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias principales
  shared_preferences: ^2.2.2
  camera: ^0.10.5+1
  google_mlkit_barcode_scanning: ^0.14.1
  google_fonts: ^6.0.0
  mobile_scanner: ^7.1.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  intl: ^0.20.2
  http: ^1.5.0
  image_picker: ^1.1.2
  syncfusion_flutter_charts: ^31.1.19
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.1
  animated_splash_screen: ^1.3.0

# ✅ SECCIÓN FLUTTER
flutter:
  uses-material-design: true
  assets:
    - assets/iconos/

# ✅ CONFIGURACIÓN ICONOS - USANDO logo1.png
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/iconos/logo1.png"
  min_sdk_android: 21

# ✅ CONFIGURACIÓN SPLASH SCREEN - USANDO Splash.png
flutter_native_splash:
  background_image: "assets/Splash.png"
  android: true
  ios: true

